config/routes.rb
RottenMangoes::Application.routes.draw do

  namespace :admin do
    resources :users
  end

  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  
  resources :users, only: [:new, :create, :show]
  resources :session, only: [:new, :create, :destroy]

  root to: 'movies#index'

end

app/models/movie.rb
class Movie < ActiveRecord::Base

  has_many :reviews
  mount_uploader :image, ImageUploader

  scope :search, lambda { |title_director, runtime_in_minutes| 
    where("title LIKE ? OR director LIKE ?", "%#{title_director}%", "%#{title_director}%").where("runtime_in_minutes #{runtime_in_minutes}") }
  scope :paged, lambda { |page| page(page).per(5) }
  
  validates :title,
    presence: true

    validates :director,
      presence: true

    validates :runtime_in_minutes,
      numericality: { only_integer: true }

    validates :description,
      presence: true

    validates :release_date,
      presence: true

    validate :release_date_is_in_the_past

    def review_average
      reviews.sum(:rating_out_of_ten)/reviews.size unless reviews.size == 0
    end

    protected

    def release_date_is_in_the_past
      if release_date.present?
        errors.add(:release_date, "should be in the past") if release_date > Date.today
      end
    end


end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user 
  belongs_to :movie

  validates :user,
    presence: true

  validates :movie,
    presence: true

  validates :text,
    presence: true

  validates :rating_out_of_ten,
    numericality: { only_integer: true}
  validates :rating_out_of_ten,
    numericality: { greater_than_or_equal_to: 1 }
  validates :rating_out_of_ten,
    numericality: { less_than_or_equal_to: 10 }
    
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :reviews, dependent: :destroy

  has_secure_password

  scope :paged, lambda { |page| page(page).per(10) }

  validates :email,
    presence: true

  validates :firstname,
    presence: true

  validates :lastname,
    presence: true

  validates :password,
    length: { in: 6..20 }, on: :create

  def full_name
    "#{firstname} #{lastname}"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :restrict_access
  before_filter :require_admin

  def index
    @users = User.all.paged(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: "#{@user.firstname} successfully created!"
    else
      render :'admin/users/new'
    end
    
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to admin_user_path(@user)
    else
      render :'admin/users/edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    DeleteUserMailer.deleted_notification(@user)
    redirect_to admin_users_path, notice: "User successfully deleted"
  end


  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :admin)
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def require_admin
    if !current_user.admin?
      flash[:alert] = "You don't have that privilege."
      redirect_to movies_path
    end
  end

  def current_user
    @current_user ||=User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index #search works but only from the original URL
    if params[:title_director]
      @movies = Movie.search(params[:title_director], params[:runtime_in_minutes]).paged(params[:page])
    else
      @movies = Movie.all.paged(params[:page])
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    restrict_access
    @movie = Movie.new
  end

  def edit
    restrict_access
    @movie = Movie.find(params[:id])
  end

  def create
    restrict_access
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def update
    restrict_access
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    restrict_access
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :remote_image_url, :description, :image
    )
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :load_movie
  before_filter :restrict_access

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end  

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Adios!"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Adios!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id #auto log in
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @reviews = Review.where(user_id: params[:id])
  end


    protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end


end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def formatted_date(date)
    date.strftime("%B %e, %Y")
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being updated:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.check_box :admin %>
    <%= f.label :admin, "admin" %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/admin/users/_user.html.erb
<h2><%= link_to admin_user_path(user) do %><%= user.full_name %><% end %> <%= "(admin)" if user.admin? %></h2> 
<h3><%= user.email %></h3>
<h2><%= link_to "edit", edit_admin_user_path(user) %> | <%= link_to "delete", admin_user_path(user), method: :delete, confirm: "You sure?" %></h2>
<hr>

app/views/admin/users/edit.html.erb
<h1>Update User Info</h1>

<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1>Admin Users</h1>
<hr>
<%= paginate @users %>


<%= render @users %>

app/views/admin/users/new.html.erb
<h1>Create a New User</h1>

<%= render 'form' %>

app/views/admin/users/show.html.erb
<%= render @user %>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <% if current_user %>
      Signed in as <%= current_user.full_name %> | <%= link_to "Log Out", session_path("current"), method: :delete %>
      <% if current_user.admin? %><%= link_to "All Users", admin_users_path %> | <%= link_to "New User", new_admin_user_path %>
      <% end %>
    <% else %>
      | <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %> 
    | <%= link_to "All Movies", movies_path %>
  </small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body><div class ="container">
<% flash.each do |key, value| %>
  <div class="alert alert-info" role="alert">
  <%= content_tag(:div, value) %>
  </div>
<% end %>
<%= yield %>
<div style="clear: both;"></div>
<%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :release_date %><br>
    <%= f.date_field :release_date %>
  </div>
  <div>
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>
  <div>
    <%= f.label :runtime_in_minutes %><br>
    <%= f.number_field :runtime_in_minutes %>
  </div>
  <div>
    <%= f.file_field :image %>
  </div>
  <div>
    <%= f.label :remote_image_url, "or image URL" %><br>
    <%= f.text_field :remote_image_url %>
  </div>
  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.submit "Submit" %> 
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div class="row">
<div class="col-md-3"><%= link_to image_tag(movie.image_url(:thumb).to_s), movie_path(movie) %></div>
<div class="col-md-9"><%= render partial: 'movie_info', locals: {movie: movie} %></div>
</div>
<hr>

app/views/movies/_movie_info.html.erb
<h2><%= link_to movie.title, movie_path(movie) %> </h2>
<h3>Average Rating: <%= movie.review_average || "0" %>/10</h3>
<h4>Release Date: <%= formatted_date(movie.release_date) %></h4>
<h4>Director: <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h4>
<p><%= movie.description %> </p>

app/views/movies/_search_form.html.erb
<div class="well">
<form>

<div class="form-group">
<%= form_tag(movies_path, :method => "get", class: "search-form") do %>
<%=label_tag :title_director, "Find movie by title or director: " %>
<%= text_field_tag :title_director, params[:title_director], placeholder: "Search" %><br/ >
</div>

<div class="form-group">
<%=label_tag :runtime_in_minutes, "and runtime in minutes: " %>
<%= select_tag(:runtime_in_minutes, options_for_select([["Any", nil],["Under 90 minutes", "<90"], ["Between 90 and 120 minutes", "BETWEEN 90 AND 120"], ["Over 120 minutes", ">120"]])) %><br />
</div>

<div class ="form-group">
<%= submit_tag "Search", :name => nil, class: "btn btn-default", id: "submit-form"%>
</div>
<%end%>

<div class ="form-group" >
<%= form_tag(movies_path, :method => "get", class: "search-form") do %>
<%= submit_tag "Clear Form", :name => nil, class: "btn btn-default", id: "clear-form"%>
</div>
<% end %>

</form>
</div>

app/views/movies/edit.html.erb
    <%= link_to "Back to this movie", movie_path(@movie) %>

    <h2>Edit this movie.</h2>
    <%= render 'form' %>

app/views/movies/index.html.erb
<h1>Rotten Mangoes</h1>
<div class="row">
<div class="col-md-4">
<h3><%= link_to "Submit a movie!", new_movie_path %></h3>
</div>
<div class="col-md-4">
<%= render 'search_form' %>
</div>
<div class="col-md-3">
</div>
</div>

<%= paginate @movies %>

<hr>
<% if @movies.present? %>
   <%= render partial: 'movie', collection: @movies %>
<% else %>
  <p>Your search returned no results<%= params[:search] %>.</p>
<% end %>
  

app/views/movies/new.html.erb
<%= link_to "Back to all movies", movies_path %>

<h2>Submit a movie!</h2>
<%= render 'form' %>

app/views/movies/show.html.erb
<%= link_to "Back to all movies", movies_path %><br/><br/>

<div class="row">
  <div class="col-md-4">
  <%= link_to image_tag(@movie.image_url(:full).to_s), movie_path(@movie) %>

  <h4> 
  <% if current_user %>
      (<%= link_to "edit", edit_movie_path(@movie) %> | <%= link_to "delete", movie_path(@movie), method: :delete, :data => { :confirm => 'You sure?' } %>)
  <% end %>
  </h4>
  </div>
  <div class="col-md-8">
  <%= render partial: 'movie_info', locals: {movie: @movie} %>
  </div>
</div>

<h3>Reviews of <em><%= @movie.title %></em></h3>
<% if current_user %>
  <%= render @movie.reviews %>
  <p><%= link_to "Write a review!", new_movie_review_path(@movie) %>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own. </p>
<% end %>

<hr>

app/views/reviews/_review.html.erb
<div class ="well">
    <p><%= link_to movie_path do %><%= review.movie.title %><% end %>
    <p><%= review.text %></p>
    <p><%= review.rating_out_of_ten %>/10</p>
    <small><%= link_to user_path do %> <%= review.user.full_name %><% end %> </small><br />
</div>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br />

<h2>Write a review of <em><%= @movie.title %></em></h2>

<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div>
      <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div>
    <%= f.label :text %><br>
    <%= f.text_area "text" %>
  </div>
  <div>
    <%= f.label :rating_out_of_ten %><br>
    <%= f.number_field :rating_out_of_ten %>
  </div>
  <div>
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/session/new.html.erb
<h1>Log In</h1>
<%= form_tag session_index_path do %>
  <div>
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div>
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div>
    <%= submit_tag "Log In" %>
  </div>

<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/show.html.erb
<hr>
  <h2><%= @user.full_name %> <%= "(admin)" if @user.admin? %></h2> 
  <h3><%= @user.email %></h3>
  <hr>
  <h3>Reviews by <%= @user.firstname %></h3>

<%= render @reviews %>